/*
 Generated by using
 ng generate component heroes
 */

import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-heroes',
  templateUrl: './heroes.component.html',
  styleUrls: ['./heroes.component.css']
})

/*
 The ngOnInit is a lifecycle hook Angular calls ngOnInit shortly after creating a component. It's a good place to put initialization logic.
 */
export class HeroesComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
